spring.application.name=yourorder-seller
spring.kafka.bootstrap-servers=localhost:9092

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/mydb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

kafka.topics.company-created=company.created
kafka.topics.company-updated=company.updated
kafka.topics.product-created=product.created
kafka.topics.product-updated=product.updated
kafka.topics.product-deleted=product.deleted
kafka.topics.order-created=order.created
kafka.topics.order-cancelled=order.cancelled
kafka.topics.stock-reserved=stock.reserved
kafka.topics.stock-released=stock.released
kafka.topics.payment-completed=payment.completed
kafka.topics.payment-failed=payment.failed
